//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centro_Acopio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Centro_Acopio()
        {
            this.Enc_CanjeoMaterial = new HashSet<Enc_CanjeoMaterial>();
        }
    
        public decimal ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> ID_Provincia { get; set; }
        public string Direccion_Exacta { get; set; }
        public string ID_Usuario { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enc_CanjeoMaterial> Enc_CanjeoMaterial { get; set; }
    }
}
