//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_CanjeoMaterial
    {
        public decimal ID_Canjeo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal ID_Material { get; set; }
    
        public virtual Enc_CanjeoMaterial Enc_CanjeoMaterial { get; set; }
        public virtual Tipo_Material Tipo_Material { get; set; }
    }
}
