//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcomonedasContexto : DbContext
    {
        public EcomonedasContexto()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billetera_Virtual> Billetera_Virtual { get; set; }
        public virtual DbSet<Centro_Acopio> Centro_Acopio { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Cupon> Cupon { get; set; }
        public virtual DbSet<Det_CanjeoMaterial> Det_CanjeoMaterial { get; set; }
        public virtual DbSet<Enc_CanjeoMaterial> Enc_CanjeoMaterial { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Material> Tipo_Material { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
