//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enc_CanjeoMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enc_CanjeoMaterial()
        {
            this.Det_CanjeoMaterial = new HashSet<Det_CanjeoMaterial>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> ID_CentroAcopio { get; set; }
        public Nullable<decimal> Cantidad_Total { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string ID_Usuario { get; set; }
    
        public virtual Centro_Acopio Centro_Acopio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_CanjeoMaterial> Det_CanjeoMaterial { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
