//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Material()
        {
            this.Det_CanjeoMaterial = new HashSet<Det_CanjeoMaterial>();
        }
    
        public decimal ID { get; set; }
        public string Nombre { get; set; }
        public string Imagen_Path { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string ID_Color { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_CanjeoMaterial> Det_CanjeoMaterial { get; set; }
    }
}
